server:
  port: 8081 # 服务绑定的端口，不写默认是8080
  servlet:
    context-path: /myredis # 服务的路径，不写默认为空
spring:
  application:
    name: service #服务名
  profiles:
    active: default # 配置文件的版本
# apollo集成
# apollo 配置应用的 appid

app.id=springboot-apollo-demo1
  # apollo meta-server地址，一般同config-server地址
apollo.meta=http://192.168.0.153:8080
  #启用apollo配置开关
apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled=true
  # apollo 使用配置的命名空间，多个以逗号分隔
apollo.bootstrap.namespaces = application